# Generated by Django 5.2.5 on 2025-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled')], default='enrolled', max_length=20),
        ),
    ]
