# Generated by Django 5.2.5 on 2025-08-23 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_status_alter_enrollment_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='rejectedenrollment',
            name='enrollment',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_date',
            new_name='enrolled_at',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.DeleteModel(
            name='AcceptedEnrollment',
        ),
        migrations.DeleteModel(
            name='EnrolledCourse',
        ),
        migrations.DeleteModel(
            name='RejectedEnrollment',
        ),
    ]
